### ISSUE TITLE
环境搭建——Ubuntu + Anaconda

### ISSUE THREAD

**Issue by noonbiteun** [noonbiteun/Blog#3]
# 0 写在前面

* **系统版本** ：Ubuntu 18.04.3 LTS
* **处理器** ：Intel®

本篇文章记录的是在Ubuntu上的Anaconda环境搭建。

    若你是windows/macOS，那么推荐你使用图形界面安装，十分便捷
    
你需要具备的前提知识：

* linux系统的基本知识
* 基本命令使用

# 1 下载

下面提供两个下载地址

* [官网下载](https://www.anaconda.com/distribution/)

* [清华镜像](https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/)

任选其中一个，前往下载`.sh`安装文件。

我需要的是对应Python3的64位Anaconda，于是这里我选择的是最新的`Anaconda3-2019.10-Linux-x86_64.sh`。
    
    请根据你的需要选择对应的版本进行下载

# 2 安装

下载完成后将`Anaconda3-2019.10-Linux-x86_64.sh`文件移动到~目录下

    ！！！note：
    这里选择将sh文件移动到~目录下是为了后续安装时不必在选择安装路径，直接安装在~目录下。
    推荐安装在~目录下

**terminal>>>**

```bash
#切换到~目录下
$ cd ~
#执行sh，开始安装
$ bash Anaconda3-2019.10-Linux-x86_64.sh
```

## 2.1 安装过程

安装过程中，看到提示

`In order to continue the installation process, please review the license agreement.`（浏览许可证协议以便继续安装）

根据提示输入回车 

在“许可证协议”界面将屏幕滚动至底，输入“yes”表示同意许可证协议内容。然后进行下一步。

之后都是选yes

# 3 添加镜像

安装完成后我们还需要为anaconda添加镜像源，不然的话下载东西会很慢很慢。。。

**terminal>>>**

```bash
#切换到home目录下
$ cd ~
#编辑 .condarc文件
$ sudo vim ./.condarc
```

添加下列内容

```
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

若添加镜像遇到问题，请参考：[Anaconda 镜像使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)

# 4 验证

**terminal>>>**

```bash
$ conda list
# 若显示已经安装的包名和版本号，则安装成功

$ conda create -n test_mirrors numpy
# 若下载比较快速的话，则镜像添加成功
```

enjoy～🤣
